deploy.yaml, Dockerfile - fixing #18 [production 9/9] RUN flask db upgrade #18 0.623 Error: Could not locate a Flask application. Use the 'flask --app' option, 'FLASK_APP' environment variable, or a 'wsgi.py' or 'app.py' file in the current directory.

diff --git a/instacloud_core/Dockerfile b/instacloud_core/Dockerfile
--- a/instacloud_core/Dockerfile
+++ b/instacloud_core/Dockerfile
@@ -30,6 +30,12 @@ COPY . .
 
 EXPOSE 5000
 
+# TESTING =======================================================================================================
+RUN test -f /app/instacloud_core/app.py || (echo "Error: Flask application file not found." && exit 1)
+RUN test -d /app/instacloud_core/migrations || (echo "Error: Database migration directory not found." && exit 1)
+RUN test -f /app/instacloud_core/.env || (echo "Error: Database configuration file (.env) not found." && exit 1)
+# ===============================================================================================================
+
 RUN flask db upgrade
 
 ENTRYPOINT ["gunicorn"]  
